### ISSUE TITLE
Game crashes upon summoning a Jokermon

### ISSUE THREAD

**Issue by VoidWillow** [segabl/pd2-jokermon#3] opened 2020-01-11 01:37 UTC
When the game goes to a heist with more than 1 day, when transitioning to the 2nd day my game CTDs if Jokermon is set to auto summon.

**Comment by segabl** [comment] 2020-01-12 10:50
what is the crash message found in ``%localappdate%/PAYDAY 2/crash.txt``?

**Comment by Ravenous212** [comment] 2020-06-03 14:24
Not certain if you're still watching this thread but I just tested this and it does in fact crash on multi-day heists, the odd thing is, there's no crash to show... however I feel like it's being caused by the mod trying to auto-summon jokers in the day end screen, since on manual it has no issue with proceeding: 
![20200603112247_1](https://user-images.githubusercontent.com/26052230/83648700-bd68fc00-a58c-11ea-9670-0ea2c41dc119.jpg)

The ones that can't accompany are causing no issue, just the ones spawning in the end screen... even more oddly it seems to randomly say which jokers were summoned and other times, like in the screenshot, says nothing while making the summon audio and the jokers voice lines playing, not 100% certain...

This ONLY happens on multi-day, since I'm guessing the game immediately sends you to the offshore casino then back to the lobby, therefore most likely despawns any jokers and preventing the crash.

**Comment by segabl** [comment] 2020-06-04 11:30
I'll have a look at this as soon as I have time for it. I'll probably have to change how the code determines the way to auto spawn jokers.

**Comment by segabl** [comment] 2020-06-04 12:16
Should be fixed with d91e20edc14d9efb9e806498fd9e07bf0b89dc60

**Closed as completed by segabl** 2020-06-04 12:16 UTC
