### ISSUE TITLE
Jokers not spawning client side

### ISSUE THREAD

**Issue by KobiiKobes** [segabl/pd2-jokermon#2] opened 2019-11-01 11:48 UTC
I cant spawn jokers client side any more. Is this intended? I loved messing around with my friend with this mod we both use it and see what npcs we can grab outa other hiests.

**Comment by segabl** [comment] 2019-11-02 14:23
Make sure you both have the newest version, as I changed some variable names. It should still work for clients if the host has the mod

**Comment by KobiiKobes** [comment] 2019-11-02 20:32
I will try deleting and reinstalling i am on the newest version i believe but i will try that and see if it helps

**Comment by segabl** [comment] 2019-12-19 20:48
Closing this as I can't reproduce the issue

**Closed as completed by segabl** 2019-12-19 20:48 UTC
